### ISSUE TITLE
Rewriting repo - getting rid of old binaries

### ISSUE THREAD

**Issue by skolima** [i-e-b/SevenDigital.Messaging#2]
I'm rewriting this repo history to get rid of old binaries that have pushed it's size to 100MB. I'll do a force-push to 7digital github repo and my own. @i-e-b - if you're ok with that, I'll do a force-push to your repo as well. @Suremaker - you'll need to do a new fork from Iain.

**Comment by skolima** [comment]
This has been performed on @7digital fork and is waiting your feedback. Repository size went down to 5MB, making the checkout time much more manageable.

**Comment by i-e-b** [comment]
Looks good to me, thanks. Feel free to force-push.

**Comment by skolima** [comment]
Done!
